### PR TITLE
FRED Data ETL

### PR DESCRIPTION
**Pull request by Sharique-stack**

### CODE REVIEW

**Comment by Sharique-stack** [comment]
1. - >        id                                             name  parent_id
2. - > 0   33058                            Automobile Loan Rates         22
3. - > 1      51                          Bankers Acceptance Rate         22
4. - > 2     121                          Certificates of Deposit         22
5. - > 3     120                                 Commercial Paper         22
6. - > 4   32348                                  Corporate Bonds         22
7. - > 5   33059                           Credit Card Loan Rates         22
8. - > 6   32298                              Eurodollar Deposits         22
9. - > 7     118  FRB Rates - discount, fed funds, primary credit         22
10. - > 8   33056                       Interest Checking Accounts         22
11. - > 9   33446                            Interest Rate Spreads         22
12. - > 10  32299                              Interest Rate Swaps         22
13. - > 11  33003                                      LIBOR Rates         22
14. - > 12  32995                             Long-Term Securities         22
15. - > 13  33055                            Money Market Accounts         22
16. - > 14    114                                   Mortgage Rates         22
17. - > 15  33057                              Personal Loan Rates         22
18. - > 16    117                             Prime Bank Loan Rate         22
19. - > 17  33491                                  Saving Accounts         22
20. - > 18    116                                   Treasury Bills         22
21. - > 19    115                       Treasury Constant Maturity         22
22. - > 20     82            Treasury Inflation-Indexed Securities         22
23. - > 21  34003                                      SONIA Rates         22

**Comment by gnommer** [comment]
Not the exact format I am expecting the metadata to be in.  Please make sure it obeys the Global Field Standards <https://docs.google.com/spreadsheets/d/1Zyn0qLI1JdZD-3EQdvpi7twzUUy3vExg80SL3CK6sWI/edit#gid=0>.

**Comment by gnommer** [comment]
and I expect the client.py file to be written as an entry point script with proper dependencies added. 
please update the requirements.txt file also with the following command

```pip3 freeze >> requirements.txt```

**Comment by Sharique-stack** [comment]
> * > ```
>   >    id                                             name  parent_id
>   > ```
> 
> * * > 0   33058                            Automobile Loan Rates         22
> 
> * * > 1      51                          Bankers Acceptance Rate         22
> 
> * * > 2     121                          Certificates of Deposit         22
> 
> * * > 3     120                                 Commercial Paper         22
> 
> * * > 4   32348                                  Corporate Bonds         22
> 
> * * > 5   33059                           Credit Card Loan Rates         22
> 
> * * > 6   32298                              Eurodollar Deposits         22
> 
> * * > 7     118  FRB Rates - discount, fed funds, primary credit         22
> 
> * * > 8   33056                       Interest Checking Accounts         22
> 
> * * > 9   33446                            Interest Rate Spreads         22
> 
> * * > 10  32299                              Interest Rate Swaps         22
> 
> * * > 11  33003                                      LIBOR Rates         22
> 
> * * > 12  32995                             Long-Term Securities         22
> 
> * * > 13  33055                            Money Market Accounts         22
> 
> * * > 14    114                                   Mortgage Rates         22
> 
> * * > 15  33057                              Personal Loan Rates         22
> 
> * * > 16    117                             Prime Bank Loan Rate         22
> 
> * * > 17  33491                                  Saving Accounts         22
> 
> * * > 18    116                                   Treasury Bills         22
> 
> * * > 19    115                       Treasury Constant Maturity         22
> 
> * * > 20     82            Treasury Inflation-Indexed Securities         22
> 
> * * > 21  34003                                      SONIA Rates         22

Dear sir, I have hard time copying it in proper dataframe format, therefore, I am sharing screenshot of my work. Good day.

**Comment by Sharique-stack** [comment]
@gnommer Sir am I done with everything now?

**Comment by gnommer** [comment]
yes and thanks for submitting the assignment

**Pull request closed without merging**
