### PR TITLE
AIS DATA ETL Pipeline

### PR DESCRIPTION
**Pull request by RohinSharma112**

### CODE REVIEW

**Comment by gnommer** [comment]
the code looks fine. but I prefer if you can complete the client.py script to trigger all the base dependencies written.
the metadata is not generated for the data you have extracted. please follow the [Global Field Standards](https://docs.google.com/spreadsheets/d/1Zyn0qLI1JdZD-3EQdvpi7twzUUy3vExg80SL3CK6sWI/edit#gid=0) and finish adding the metadata

**Comment by RohinSharma112** [comment]
How much time do I have to complete this given task?
Thanks & Regards,Rohin Sharma

Sent from Yahoo Mail on Android 
 
  On Mon, 18 Oct 2021 at 6:41 pm, Chinta Geetha Charan ***@***.***> wrote:   


the code looks fine. but I prefer if you can complete the client.py script to trigger all the base dependencies written.
the metadata is not generated for the data you have extracted. please follow the Global Field Standards and finish adding the metadata

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gnommer** [comment]
if you can finish in 2 days. I will do a final review and we can schedule a call to discuss the results.

**Comment by RohinSharma112** [comment]
Is meta data required within the main data or as a separate file?
Thanks & Regards,Rohin Sharma    On Monday, 18 October, 2021, 06:50:06 pm IST, Chinta Geetha Charan Reddy ***@***.***> wrote:  
 
 


if you can finish in 2 days. I will do a final review and we can schedule a call to discuss the results.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gnommer** [comment]
Seperate as it is to be ingested in a different data store

**Comment by RohinSharma112** [comment]
I have made the required changes. Please check and review the code.Thank you for clarifying my doubts and helping me.
Thanks & Regards,Rohin Sharma
    On Tuesday, 19 October, 2021, 01:28:09 pm IST, Chinta Geetha Charan Reddy ***@***.***> wrote:  
 
 

Seperate as it is to be ingested in a different data store

Sent from my iPhone

> On 19-Oct-2021, at 11:34, RohinSharma112 ***@***.***> wrote:
> 
> ﻿
> Is meta data required within the main data or as a separate file?
> Thanks & Regards,Rohin Sharma On Monday, 18 October, 2021, 06:50:06 pm IST, Chinta Geetha Charan Reddy ***@***.***> wrote: 
> 
> 
> 
> 
> if you can finish in 2 days. I will do a final review and we can schedule a call to discuss the results.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gnommer** [comment]
hi Rohin, impressed so far with the assignment. shared a meeting invite on Internshala. do follow up on that and thanks for submitting the assignment

**Comment by RohinSharma112** [comment]
I have confirmed my availability on the Internshala. Thank you again for your help.
Regards,Rohin Sharma
    On Wednesday, 20 October, 2021, 03:56:35 pm IST, Chinta Geetha Charan Reddy ***@***.***> wrote:  
 
 


hi Rohin, impressed so far with the assignment. shared a meeting invite on Internshala. do follow up on that and thanks for submitting the assignment

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
