### PR TITLE
FRED_BIS_webpage_scrapper

### PR DESCRIPTION
**Pull request by codeprofile**

### CODE REVIEW

**Comment by codeprofile** [comment]
@gnommer and @KayvanShah1 :- Please Review

**Comment by ShubhamShaswat** [comment]
Please mention your full name and Internshala profile link here

**Comment by codeprofile** [comment]
Full Name:- Laxmi Mandire Sarki
Internshala Profile Link : https://internshala.com/student/resume?detail_source=resume_intermediate

**Comment by ShubhamShaswat** [comment]
Code Reviewed and Interviewed

**Comment by ShubhamShaswat** [comment]
The assignment has ended now so kindly close the PR.

**Pull request closed without merging**
