### PR TITLE
Taiyo internship task for data engineer role

### PR DESCRIPTION
**Pull request by aayushpandey1703**
Please check my internship task for data enginneer role

### CODE REVIEW

**Comment by ShubhamShaswat** [comment]
Apart from the third point mentioned in the tasks, everything is pretty much covered. We want the final csv file as same format as this one https://www.bis.org/statistics/full_cbpol_d_csv_row.zip. The country should be an individual column as well as time period. Look at the original file and compare it with this file https://www.bis.org/statistics/full_cbpol_d_csv_row.zip to proceed with the further changes.

**Comment by aayushpandey1703** [comment]
Ok, so the time period must be separate column and each country must be another set of columns, right?

**Comment by ShubhamShaswat** [comment]
Yes, In current dataset the country is just an individual row so we want to transpose it into column.

**Comment by aayushpandey1703** [comment]
Hi, Please have a look at updated files

**Pull request closed without merging**
